#include "../../src/k_conv2D.cpp"
#include "../../src/add.cpp"
#include "../../src/cvt.cpp"
#include "../../src/stm.cpp"
#include "../../src/direct_convolution.cpp"
#include "../../src/dws_convolution.cpp"
#include "../../src/join_split.cpp"
#include "../../src/pooling.cpp"
#include "../../src/mul.cpp"
#include "../../src/padding.cpp"
#include "../../src/read.cpp"
#include "../../src/relu.cpp"
#include "../../src/serialization.cpp"
#include "../../src/winograd_convolution.cpp"
#include "../../src/write.cpp"

